'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SQLiteConn() As String
            Get
                Return CType(Me("SQLiteConn"),String)
            End Get
            Set
                Me("SQLiteConn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property OP_OCR_tessdata_folder() As String
            Get
                Return CType(Me("OP_OCR_tessdata_folder"),String)
            End Get
            Set
                Me("OP_OCR_tessdata_folder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property OP_OCR_temp_folder() As String
            Get
                Return CType(Me("OP_OCR_temp_folder"),String)
            End Get
            Set
                Me("OP_OCR_temp_folder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property OP_GEN_DBFile() As String
            Get
                Return CType(Me("OP_GEN_DBFile"),String)
            End Get
            Set
                Me("OP_GEN_DBFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EliteDangerous32")>  _
        Public Property OP_GEN_EDProcess() As String
            Get
                Return CType(Me("OP_GEN_EDProcess"),String)
            End Get
            Set
                Me("OP_GEN_EDProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("31")>  _
        Public Property OP_OCR_Contrast() As String
            Get
                Return CType(Me("OP_OCR_Contrast"),String)
            End Get
            Set
                Me("OP_OCR_Contrast") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.98")>  _
        Public Property OP_OCR_Gamma() As String
            Get
                Return CType(Me("OP_OCR_Gamma"),String)
            End Get
            Set
                Me("OP_OCR_Gamma") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("big")>  _
        Public Property OP_OCR_Language() As String
            Get
                Return CType(Me("OP_OCR_Language"),String)
            End Get
            Set
                Me("OP_OCR_Language") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("67")>  _
        Public Property OP_OCR_Confidence() As String
            Get
                Return CType(Me("OP_OCR_Confidence"),String)
            End Get
            Set
                Me("OP_OCR_Confidence") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property OP_OCR_ScalingFactor() As String
            Get
                Return CType(Me("OP_OCR_ScalingFactor"),String)
            End Get
            Set
                Me("OP_OCR_ScalingFactor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property OP_OCR_Grayscale_Type() As Integer
            Get
                Return CType(Me("OP_OCR_Grayscale_Type"),Integer)
            End Get
            Set
                Me("OP_OCR_Grayscale_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("65")>  _
        Public Property OP_OCR_Black_Threshold() As Integer
            Get
                Return CType(Me("OP_OCR_Black_Threshold"),Integer)
            End Get
            Set
                Me("OP_OCR_Black_Threshold") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property offline_testing() As Integer
            Get
                Return CType(Me("offline_testing"),Integer)
            End Get
            Set
                Me("offline_testing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1180, 600")>  _
        Public Property WIN_Default_Min_Size() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_Default_Min_Size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_Default_Min_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1090, 600")>  _
        Public Property WIN_OCR_DEF_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_OCR_DEF_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_OCR_DEF_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("715, 600")>  _
        Public Property WIN_SYSADD_DEF_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_SYSADD_DEF_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_SYSADD_DEF_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1250, 600")>  _
        Public Property WIN_BC_DEF_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_BC_DEF_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_BC_DEF_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1130, 600")>  _
        Public Property WIN_BS_DEF_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_BS_DEF_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_BS_DEF_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1150, 625")>  _
        Public Property WIN_FT_DEF_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_FT_DEF_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_FT_DEF_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("605, 570")>  _
        Public Property WIN_MC_DEF_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_MC_DEF_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_MC_DEF_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property OP_OCR_DeleteScreenshot() As Boolean
            Get
                Return CType(Me("OP_OCR_DeleteScreenshot"),Boolean)
            End Get
            Set
                Me("OP_OCR_DeleteScreenshot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SpecialDirectories.MyPictures + ""\Frontier Developments\Elite Dangerous""")>  _
        Public Property OP_OCR_ScreenshotDirectory() As String
            Get
                Return CType(Me("OP_OCR_ScreenshotDirectory"),String)
            End Get
            Set
                Me("OP_OCR_ScreenshotDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1090, 600")>  _
        Public Property WIN_OCR_USR_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_OCR_USR_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_OCR_USR_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("715, 600")>  _
        Public Property WIN_SYSADD_USR_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_SYSADD_USR_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_SYSADD_USR_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1130, 600")>  _
        Public Property WIN_BS_USR_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_BS_USR_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_BS_USR_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1250, 600")>  _
        Public Property WIN_BC_USR_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_BC_USR_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_BC_USR_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1450, 625")>  _
        Public Property WIN_FT_USR_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_FT_USR_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_FT_USR_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1150, 600")>  _
        Public Property WIN_COM_USR_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_COM_USR_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_COM_USR_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("605, 570")>  _
        Public Property WIN_MC_USR_SIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("WIN_MC_USR_SIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WIN_MC_USR_SIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property OP_OCR_PVariance() As String
            Get
                Return CType(Me("OP_OCR_PVariance"),String)
            End Get
            Set
                Me("OP_OCR_PVariance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property GEN_UPGRADE_FLAG() As String
            Get
                Return CType(Me("GEN_UPGRADE_FLAG"),String)
            End Get
            Set
                Me("GEN_UPGRADE_FLAG") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.EliteDangerousAssistant.My.MySettings
            Get
                Return Global.EliteDangerousAssistant.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
